# Generated by Django 5.2.10 on 2026-02-04 19:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('episode_id', models.IntegerField()),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=300)),
                ('producer', models.CharField(max_length=300)),
                ('release_date', models.DateTimeField()),
                ('characters', models.URLField(max_length=4000)),
                ('planets', models.URLField(max_length=1000)),
                ('starships', models.URLField(max_length=1000)),
                ('vehicles', models.URLField(max_length=1000)),
                ('species', models.URLField(max_length=1000)),
                ('created', models.DateTimeField()),
                ('edited', models.DateTimeField()),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('mass', models.CharField(blank=True, max_length=100)),
                ('hair_color', models.CharField(blank=True, max_length=100)),
                ('skin_color', models.CharField(blank=True, max_length=100)),
                ('eye_color', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('homeworld', models.URLField(default='homeworld', max_length=1000)),
                ('films', models.URLField(default='films', max_length=1000)),
                ('species', models.URLField(default='species', max_length=1000)),
                ('vehicles', models.URLField(default='vehicle', max_length=1000)),
                ('starships', models.URLField(default='starship', max_length=1000)),
                ('created', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rotation_period', models.CharField(max_length=100)),
                ('orbital_period', models.CharField(max_length=100)),
                ('diameter', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('gravity', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
                ('surface_water', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=100)),
                ('residents', models.URLField(verbose_name=models.URLField(max_length=1000))),
                ('films', models.URLField(verbose_name=models.URLField(max_length=1000))),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('average_height', models.CharField(max_length=200)),
                ('skin_colors', models.CharField(max_length=200)),
                ('hair_colors', models.CharField(max_length=200)),
                ('eye_colors', models.CharField(max_length=200)),
                ('average_lifespan', models.CharField(max_length=200)),
                ('homeworld', models.URLField(max_length=1000, null=True)),
                ('language', models.CharField(max_length=100)),
                ('people', models.URLField(max_length=1000)),
                ('films', models.URLField(default='films', max_length=1000)),
                ('url', models.URLField(default='url')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('cost_in_credits', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('max_atmosphering_speed', models.CharField(max_length=100)),
                ('crew', models.CharField(max_length=100)),
                ('passengers', models.CharField(max_length=100)),
                ('cargo_capacity', models.CharField(max_length=100)),
                ('consumables', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transport')),
                ('hyperdrive_rating', models.CharField(max_length=100)),
                ('MGLT', models.CharField(max_length=100)),
                ('starship_class', models.CharField(max_length=100)),
                ('pilots', models.URLField(max_length=1000)),
            ],
            bases=('core.transport',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transport')),
                ('vehicle_class', models.CharField(max_length=200)),
            ],
            bases=('core.transport',),
        ),
    ]
