# Generated by Django 5.2.10 on 2026-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='pilots',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pilots',
            field=models.ManyToManyField(blank=True, to='core.people'),
        ),
    ]
