# Generated by Django 5.2.10 on 2026-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_vehicle_pilots_vehicle_pilots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='pilots',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pilots',
            field=models.URLField(default='pilots', max_length=1000),
        ),
    ]
