# Generated by Django 5.2.10 on 2026-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vehicle_pilots_vehicle_pilots'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='movies',
            field=models.ManyToManyField(related_name='roles', to='core.film'),
        ),
    ]
