# Generated by Django 5.2.10 on 2026-02-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_people_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='movies',
        ),
    ]
